const data = {
  personalInfo: {
    name: "RIO GRIYA PUTRA",
    title: "Full Stack Developer",
    photo: "https://via.placeholder.com/", // Replace with your photo URL,
    contact: {
      email: "riogriyaputra@gmail.com",
      phone: "+6281386308255",
      github: "github.com/rioogp",
      linkedin: "linkedin.com/in/rio-griya-putra",
    },
    links: {
      curriculumVitae:
        "https://drive.google.com/file/d/1v0g3j4x5k7l8z9q8q8q8q8q8q/view?usp=sharing",
      portfolio: "https://riogriyaputra.github.io/",
    },
    profileSummary:
      "Fullstack Developer with over 1 year of experience in building end-to-end web and mobile applications using Java, Kotlin, Spring Boot for backend and ReactJS for frontend. Skilled in designing scalable APIs, managing relational databases with SQL, and crafting responsive, user-centric interfaces. Experienced in integrating frontend and backend seamlessly, optimizing performance, and maintaining clean, modular code across the stack. Passionate about delivering impactful products through continuous learning and collaboration. Always up to date with the latest in web technologies and best development practices.",
  },
  education: [
    {
      institution: "Universitas YARSI",
      degree: "Informatics Engineering",
      period: "2020 – 2024",
      location: "Jakarta, Indonesia",
      gpa: "3.89 out of 4.00",
      details: [
        "Assistant Lecturer in Basic Programming [2021]",
        "Assistant Lecturer in Basic Database [2022]",
        "Assistant Lecturer in Object Oriented Programming [2023]",
        "Assistant Lecturer in Basic Networking [2023]",
        "Documentation Staff of HIMFO FTI [2022]",
        "MSIB Batch 3 – Web Developer, Independent Study Program at Hacktiv8 [2022]",
        "MSIB Batch 4 – Android Engineering, Independent Study Program at Binar Academy [2023]",
      ],
    },
  ],
  experience: [
    {
      title: "Kampus Merdeka: Independent Study - Android Engineering",
      company: "Binar Academy",
      period: "Feb 2023 – Jun 2023",
      location: "Jakarta, Indonesia",
      description: [
        "Mastered Kotlin fundamentals, including syntax, data structures, control flow, classes, objects, and functions.",
        "Developed Android applications with a focus on UI design, activity management, fragments, and seamless navigation.",
        "Utilized Android development tools effectively to implement clean architecture and maintain high code quality.",
        "Integrated key Android components such as ViewModel, Data Binding, and LiveData for efficient state management.",
        "Implemented server communication using Retrofit and optimized local data storage with ROOM.",
        "Managed background processes and applied best practices in Android app development.",
        "Executed app development lifecycle, including design, implementation, and quality assurance for unpublished apps.",
        "Collaborated with Fullstack Developer teams to build E-Flight App, a flight booking application.",
      ],
    },
    {
      title: "Kampus Merdeka: Independent Study - Web Developer",
      company: "Hacktiv8",
      period: "Aug 2022 – Dec 2022",
      location: "Jakarta, Indonesia",
      description: [
        "Completed an intensive program focused on acquiring practical web development skills.",
        "Mastered web development fundamentals, including HTML, CSS, and JavaScript basics.",
        "Developed skills in creating responsive web interfaces adaptable to various devices.",
        "Gained a comprehensive understanding of the full web development lifecycle (development to deployment).",
        "Acquired practical experience in deploying web applications using online platforms.",
        "Successfully designed, built, and deployed Demo App as part of the program.",
      ],
    },
    {
      title: "Object Oriented Programming Course - Assistant Lecturer",
      company: "Universitas YARSI",
      period: "Sep 2022 – Jan 2023",
      location: "Jakarta, Indonesia",
      description: [
        "Facilitated the delivery of Object-Oriented Programming concepts, emphasizing the application of design patterns.",
        "Guided students in mastering complex programming concepts and enhancing coding skills through lectures, hands-on assignments, and personalized support.",
        "Led engaging lectures and discussions to simplify challenging topics, fostering a collaborative and inclusive learning environment.",
        "Provided one-on-one mentorship, assisting students in troubleshooting coding issues and strengthening their development abilities.",
        "Designed and implemented weekly programming tasks to reinforce key course concepts and encourage practical application.",
        "Evaluated student assignments, offering constructive feedback to drive skill development and inspire creativity.",
      ],
    },
    {
      title: "Basic Database Course - Assistant Lecturer",
      company: "Universitas YARSI",
      period: "Feb 2022 – Jun 2022",
      location: "Jakarta, Indonesia",
      description: [
        "Facilitated the teaching of Database Management Systems, SQL, and Data Modeling, ensuring comprehensive understanding among students.",
        "Developed and delivered detailed teaching materials, including case studies and exercises, covering essential concepts such as:",
        "Business Rules (Structural and Procedural)",
        "Conceptual and Logical Data Modeling",
        "Matrix Diagrams, Supertype and Subtype Entities",
        "Database Normalization (1NF, 2NF, 3NF)",
        "Transformation from Logical to Physical Data Models",
        "Designed advanced SQL exercises using PostgreSQL, focusing on practical application, including:",
        "Data Definition Language (DDL) and Data Manipulation Language (DML)",
        "Complex SQL queries with SELECT, Joins, Grouping (GROUP BY), and Conditional Filtering (HAVING clause)",
        "Result ordering with ORDER BY for data organization and presentation",
      ],
    },
    {
      title: "Basic Programming Course - Assistant Lecturer",
      company: "Universitas YARSI",
      period: "Sep 2021 – Jan 2022",
      location: "Jakarta, Indonesia",
      description: [
        "Facilitated the teaching of fundamental programming concepts, focusing on algorithms, basic syntax, and problem-solving techniques.",
        "Developed and curated comprehensive teaching materials and assignments for Java, covering key topics such as:",
        "Introduction to Programming",
        "Variables, Data Types, and Type Conversion",
        "Arrays and Data Manipulation",
        "Passing by Value vs. Passing by Reference",
        "Control Flow Structures (if, switch, loops)",
        "Non-Void vs. Void Methods and Their Applications",
      ],
    },
  ],
  projects: [
    {
      name: "K-etik Web App, Komite Etik Website",
      image: "https://via.placeholder.com/", // Replace with project image
      period: "Feb 2024 – Jul 2024",
      associatedWith: "Universitas YARSI - Project",
      description:
        "K-Etik is a web-based platform in collaboration with the YARSI University Ethics Committee, designed to streamline the submission, review, and approval process for research ethics proposals. The platform supports multiple user roles, including Applicants, Administrators, Reviewers, and Ethics Committee Chairs, improving workflow efficiency.",
      period: "Feb 2024 – Jul 2024",
      keyFeaturesAndResponsibilities: [
        "Led overall application design and managed client requirements from specification gathering to final delivery.",
        "Built the responsive frontend using React, Vite, Tailwind CSS, and Material UI, implementing role-specific interfaces.",
        "Developed the backend API using Node.js, Express.js, and MongoDB (with Mongoose) for data management and business logic.",
        "Implemented secure authentication and authorization using JWT and Bcrypt.js.",
        "Managed asynchronous data fetching and state on the frontend effectively with React Query.",
        "Handled proposal submission workflows, including file uploads (Multer) and email notifications (NodeMailer).",
      ],
      technologies: [
        "React",
        "Vite",
        "Tailwind CSS",
        "Material UI",
        "Node.js",
        "Express.js",
        "MongoDB",
        "Mongoose",
        "JWT",
        "Bcrypt.js",
        "React Query",
        "Multer",
        "NodeMailer",
      ],
    },
    {
      name: "TravelIn - Domestic Flight Booking App (Android)",
      image: "https://via.placeholder.com/", // Replace with project image
      period: "Feb 2023 – Jun 2023",
      associatedWith: "Binar Academy - Project",
      description:
        "TravelIn is a comprehensive application designed to assist users in booking domestic airline tickets. The app is accessible via both web and Android platforms, offering a seamless user experience through modern technologies such as MVVM architecture, Kotlin Coroutines for concurrency, and Firebase for real-time data management.",
      period: "Feb 2023 – Jun 2023",
      keyFeaturesAndTechnologies: [
        "Integrated RESTful APIs using Retrofit for real-time flight data synchronization.",
        "Implemented offline data storage and caching using Room and DataStore.",
        "Utilized Dagger-Hilt for dependency injection, enhancing modularity.",
        "Applied Clean Architecture principles to ensure scalability and testability.",
        "Built an intuitive and responsive UI/UX with Material Design and Navigation Component.",
      ],
      technologies: [
        "Android",
        "Kotlin",
        "MVVM",
        "Kotlin Coroutines",
        "Firebase",
        "RESTful API",
        "Retrofit",
        "Room",
        "DataStore",
        "Dagger-Hilt",
        "Clean Architecture",
        "Material Design",
        "Navigation Component",
      ],
    },
  ],
  technicalSkills: [
    "ReactJS",
    "NodeJS",
    "Java",
    "Kotlin",
    "Git",
    "CSS3",
    "JavaScript",
    "Kotlin",
    "SQL",
    "HTML5",
    "Spring Boot",
    "RESTful API",
    "Docker",
    "Postman",
    "Google Cloud Platform",
  ],
  certificatesAndReports: [
    {
      title: "Learn Basic Web Programming",
      issuer: "Dicoding",
      type: "Certificate",
    },
    {
      title: "Kampus Merdeka: Independent Study Program - Web Developer",
      issuer: "Hacktiv8",
      type: "Certificate/Report", // Assuming based on context, could be split if needed
    },
    {
      title: "Kampus Merdeka: Independent Study Program - Android Engineering",
      issuer: "Binar Academy",
      type: "Certificate",
    },
    {
      title: "Kampus Merdeka: Independent Study Program - Android Engineering",
      issuer: "Binar Academy",
      type: "Final Report",
    },
  ],
  organization: [
    {
      name: "Informatics Student Association",
      role: "Documentation Staff",
      period: "2022 – 2023",
      location: "Jakarta, Indonesia",
    },
  ],
};
